#!/usr/bin/env php
<?php
// application.php

require __DIR__.'/vendor/autoload.php';
require __DIR__.'/SlidingBlockCommand.php';
use Symfony\Component\Console\Application;


$application = new Application();

$application->add(new SlidingBlockCommand());

$application->run();